#goal definition
string  command
string  id
geometry_msgs/PoseStamped obj_pose
geometry_msgs/PoseStamped location_pose
moveit_msgs/AttachedCollisionObject grasped_object
bool stand
---
#result definition
string error_string

---
#feedback
# string feedback