#goal definition
#geometry_msgs/PoseStamped pose

float64 posi_x   # 移動先の目標位置 (x座標)
float64 posi_y   # 移動先の目標位置 (y座標)
---
#result definition
string error_string
bool success 
#geometry_msgs/PoseStamped updated_obj_pose
---
#feedback
# string feedback