#goal definition
string command
string id
string label
geometry_msgs/PoseStamped pose
---
#result definition
string error_string
geometry_msgs/Pose pose
geometry_msgs/PoseStamped[] poses
---
#feedback
# string feedback